--- Makefile.old	2009-01-27 19:39:38.000000000 +0100
+++ Makefile	2009-01-27 19:52:59.000000000 +0100
@@ -1,8 +1,8 @@
 BINARY=libcowdancer.so cow-shell cowbuilder qemubuilder cowdancer-ilistcreate \
 	cowdancer-ilistdump
-INSTALL_DIR=install -d -o root -g root -m 755
-INSTALL_FILE=install -o root -g root -m 644
-INSTALL_PROGRAM=install -o root -g root -m 755
+INSTALL_DIR=install -d -m 755
+INSTALL_FILE=install -m 644
+INSTALL_PROGRAM=install -m 755
 DESTDIR=
 PREFIX=/usr
 LIBDIR=$(PREFIX)/lib
@@ -12,6 +12,7 @@
 
 install: $(BINARY)
 	$(INSTALL_DIR) $(DESTDIR)${PREFIX}/bin
+	$(INSTALL_DIR) $(DESTDIR)${PREFIX}/sbin
 	$(INSTALL_DIR) $(DESTDIR)${LIBDIR}/cowdancer
 	$(INSTALL_DIR) $(DESTDIR)${PREFIX}/share/man/man1
 	$(INSTALL_DIR) $(DESTDIR)${PREFIX}/share/man/man8
